version: "3.8"

services:
  api:
    container_name: api
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/app
      - ./api/node_modules:/usr/src/app/node_modules
    command: sh -c "npm install && npm run start:dev"
  db:
    container_name: db
    ports:
      - 5432:5432
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data: {}
