name: Deploy NestJS API to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19

      - name: Install dependencies
        working-directory: api
        run: |
          npm ci

      - name: Build `.env` file
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          echo "$DATABASE_URL" >> .env
          echo "$JWT_SECRET" >> .env
          cat .env

      - name: Deploy to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $USER@$HOST "GIT_SSH_COMMAND='ssh -i ~/.ssh/deploy_key  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' git clone git@github.com:ESGI-SBOUDACHER/Nest-TS-5IW4-G7.git /var/www/app || (cd /var/www/app && git pull)"
          ssh -i private_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $USER@$HOST "cd /var/www/app/api && npm ci && npm run start:prod"
